spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "!1q2w3e4r!"

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true


server:
  port: 80

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


token:
  expiration_time: 86400000
  secret_key: userToken